Create TABLE Players_IE1(
    player_id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT,
    nickname TEXT,
    position TEXT,
    gender TEXT,
    size TEXT,
    element TEXT,
    fp INTEGER,
    tp INTEGER,
    kick INTEGER,
    body INTEGER,
    control INTEGER,
    guard INTEGER,
    speed INTEGER,
    stamina INTEGER,
    guts INTEGER,
    freedom INTEGER,
    move1 TEXT,
    lvlmove1 TEXT,
    move2 TEXT,
    lvlmove2 TEXT,
    move3 TEXT,
    lvlmove3 TEXT,
    move4 TEXT,
    lvlmove4 TEXT
);

Create TABLE Players_IE2(
    player_id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT,
    nickname TEXT,
    position TEXT,
    gender TEXT,
    size TEXT,
    element TEXT,
    fp INTEGER,
    tp INTEGER,
    kick INTEGER,
    body INTEGER,
    control INTEGER,
    guard INTEGER,
    speed INTEGER,
    stamina INTEGER,
    guts INTEGER,
    freedom INTEGER,
    move1 TEXT,
    lvlmove1 TEXT,
    move2 TEXT,
    lvlmove2 TEXT,
    move3 TEXT,
    lvlmove3 TEXT,
    move4 TEXT,
    lvlmove4 TEXT
);

Create TABLE Players_IE3(
    player_id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT,
    nickname TEXT,
    position TEXT,
    gender TEXT,
    size TEXT,
    element TEXT,
    fp INTEGER,
    tp INTEGER,
    kick INTEGER,
    body INTEGER,
    control INTEGER,
    guard INTEGER,
    speed INTEGER,
    stamina INTEGER,
    guts INTEGER,
    freedom INTEGER,
    move1 TEXT,
    lvlmove1 TEXT,
    move2 TEXT,
    lvlmove2 TEXT,
    move3 TEXT,
    lvlmove3 TEXT,
    move4 TEXT,
    lvlmove4 TEXT
);